### ISSUE TITLE
Missing sprites

### ISSUE THREAD

**Issue by MIGHTYCLIMBER** [ThirstyBoi/TerraDustry#1]
Unit enthusiast here,I saw some ohnoes at ur unit.including that walking brain and that wall of flesh thingy,can you sprite them?

**Comment by ThirstyBoi** [comment]
Abomination (The Brain Crab), Terror are no longer relevant to the mod, i forgot to remove their jsons, aa for the wall of flesh im also going to remove it as it was just a failed experiment
